### ISSUE TITLE
g 1 erreur

### ISSUE THREAD

**Issue by Seowlfh** [Pivouane/beautiful_pacman#1]
Bonjour j'ai un petit problème quand j'essaie de lancer votre script sur mes fichiers du coup quand je le lance j'ai cette erreur je comprends pas vraiment cette erreur est-ce que vous pouvez m'aider svp ?

```
[xmldom error]	element parse error: Error: invalid tagName:std::pair<const 
@#[line:7,col:174]
[xmldom warning]	attribute "int," missed value!! "int," instead2!! 
@#[line:7,col:184]
[xmldom error]	element parse error: Error: invalid attribute:int, 
@#[line:7,col:184]
[xmldom error]	element parse error: Error: invalid tagName:_Val, 
@#[line:7,col:270]
[xmldom warning]	attribute "int," missed value!! "int," instead2!! 
@#[line:7,col:357]
[xmldom error]	element parse error: Error: invalid attribute:int, 
@#[line:7,col:357]
[xmldom warning]	attribute "int," missed value!! "int," instead2!! 
@#[line:7,col:394]
[xmldom error]	element parse error: Error: invalid attribute:int, 
@#[line:7,col:394]
[xmldom warning]	attribute "int," missed value!! "int," instead2!! 
@#[line:7,col:432]
[xmldom error]	element parse error: Error: invalid attribute:int, 
@#[line:7,col:432]
[xmldom error]	element parse error: Error: invalid tagName:std::pair<const 
@#[line:7,col:519]
[xmldom warning]	attribute "int," missed value!! "int," instead2!! 
@#[line:7,col:529]
[xmldom error]	element parse error: Error: invalid attribute:int, 
@#[line:7,col:529]
[xmldom error]	element parse error: Error: invalid tagName:_Val, 
@#[line:7,col:616]
[xmldom warning]	attribute "int," missed value!! "int," instead2!! 
@#[line:7,col:703]
[xmldom error]	element parse error: Error: invalid attribute:int, 
@#[line:7,col:703]
[xmldom warning]	attribute "int," missed value!! "int," instead2!! 
@#[line:7,col:740]
[xmldom error]	element parse error: Error: invalid attribute:int, 
@#[line:7,col:740]
[xmldom warning]	attribute "int," missed value!! "int," instead2!! 
@#[line:7,col:778]
[xmldom error]	element parse error: Error: invalid attribute:int, 
@#[line:7,col:778]
[xmldom error]	element parse error: Error: invalid tagName:_Key, 
@#[line:7,col:878]
[xmldom warning]	attribute "int," missed value!! "int," instead2!! 
@#[line:7,col:1003]
[xmldom error]	element parse error: Error: invalid attribute:int, 
@#[line:7,col:1003]
[xmldom error]	element parse error: Error: invalid tagName:std::pair<const 
@#[line:7,col:1053]
[xmldom warning]	attribute "int," missed value!! "int," instead2!! 
@#[line:7,col:1063]
[xmldom error]	element parse error: Error: invalid attribute:int, 
@#[line:7,col:1063]
[xmldom error]	element parse error: Error: invalid tagName:std::pair<const 
@#[line:7,col:1136]
[xmldom warning]	attribute "int," missed value!! "int," instead2!! 
@#[line:7,col:1146]
[xmldom error]	element parse error: Error: invalid attribute:int, 
@#[line:7,col:1146]
[xmldom warning]	attribute "Key," missed value!! "Key," instead2!! 
@#[line:7,col:1246]
[xmldom error]	element parse error: Error: invalid attribute:Key, 
@#[line:7,col:1246]
[xmldom error]	element parse error: Error: invalid tagName:std::pair<const 
@#[line:7,col:1423]
[xmldom warning]	attribute "int," missed value!! "int," instead2!! 
@#[line:7,col:1433]
[xmldom error]	element parse error: Error: invalid attribute:int, 
@#[line:7,col:1433]
[xmldom error]	element parse error: Error: invalid tagName:std::pair<const 
@#[line:7,col:174]
[xmldom warning]	attribute "int," missed value!! "int," instead2!! 
@#[line:7,col:184]
[xmldom error]	element parse error: Error: invalid attribute:int, 
@#[line:7,col:184]
[xmldom error]	element parse error: Error: invalid tagName:_Val, 
@#[line:7,col:270]
[xmldom warning]	attribute "int," missed value!! "int," instead2!! 
@#[line:7,col:357]
[xmldom error]	element parse error: Error: invalid attribute:int, 
@#[line:7,col:357]
[xmldom warning]	attribute "int," missed value!! "int," instead2!! 
@#[line:7,col:394]
[xmldom error]	element parse error: Error: invalid attribute:int, 
@#[line:7,col:394]
[xmldom warning]	attribute "int," missed value!! "int," instead2!! 
@#[line:7,col:432]
[xmldom error]	element parse error: Error: invalid attribute:int, 
@#[line:7,col:432]
[xmldom error]	element parse error: Error: invalid tagName:std::pair<const 
@#[line:7,col:519]
[xmldom warning]	attribute "int," missed value!! "int," instead2!! 
@#[line:7,col:529]
[xmldom error]	element parse error: Error: invalid attribute:int, 
@#[line:7,col:529]
[xmldom error]	element parse error: Error: invalid tagName:_Val, 
@#[line:7,col:616]
[xmldom warning]	attribute "int," missed value!! "int," instead2!! 
@#[line:7,col:703]
[xmldom error]	element parse error: Error: invalid attribute:int, 
@#[line:7,col:703]
[xmldom warning]	attribute "int," missed value!! "int," instead2!! 
@#[line:7,col:740]
[xmldom error]	element parse error: Error: invalid attribute:int, 
@#[line:7,col:740]
[xmldom warning]	attribute "int," missed value!! "int," instead2!! 
@#[line:7,col:778]
[xmldom error]	element parse error: Error: invalid attribute:int, 
@#[line:7,col:778]
[xmldom error]	element parse error: Error: invalid tagName:_Key, 
@#[line:7,col:878]
[xmldom warning]	attribute "int," missed value!! "int," instead2!! 
@#[line:7,col:1003]
[xmldom error]	element parse error: Error: invalid attribute:int, 
@#[line:7,col:1003]
[xmldom error]	element parse error: Error: invalid tagName:std::pair<const 
@#[line:7,col:1053]
[xmldom warning]	attribute "int," missed value!! "int," instead2!! 
@#[line:7,col:1063]
[xmldom error]	element parse error: Error: invalid attribute:int, 
@#[line:7,col:1063]
[xmldom error]	element parse error: Error: invalid tagName:std::pair<const 
@#[line:7,col:1136]
[xmldom warning]	attribute "int," missed value!! "int," instead2!! 
@#[line:7,col:1146]
[xmldom error]	element parse error: Error: invalid attribute:int, 
@#[line:7,col:1146]
[xmldom warning]	attribute "Key," missed value!! "Key," instead2!! 
@#[line:7,col:1246]
[xmldom error]	element parse error: Error: invalid attribute:Key, 
@#[line:7,col:1246]
[xmldom error]	element parse error: Error: invalid tagName:std::pair<const 
@#[line:7,col:1423]
[xmldom warning]	attribute "int," missed value!! "int," instead2!! 
@#[line:7,col:1433]
[xmldom error]	element parse error: Error: invalid attribute:int, 
@#[line:7,col:1433]
/tmp/beautiful_pacman/node_modules/googlethis/lib/core/main.js:222
    throw new Utils.SearchError(data[53]?.[1] || 'Unexpected response structure', data[53]?.[2] || data);
          ^

SearchError: Looks like there aren’t any matches for your search
    at Object.image (/tmp/beautiful_pacman/node_modules/googlethis/lib/core/main.js:222:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async searchImages (/tmp/beautiful_pacman/search.js:4:19)
    at async /tmp/beautiful_pacman/index.js:38:23 {
  info: [
    null,
    [],
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    [],
    null,
    null,
    null,
    null,
    false,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    [
      null,
      [
        [
          '/search?q\\u003dfront+florestan+fargetton\\u0026source\\u003dlmns',
          null,
          null,
          'All',
          false,
          null,
          null,
          null,
          null,
          'WEB',
          [ 0 ],
          null,
          null,
          0
        ],
        [
          '/search?q\\u003dfront+florestan+fargetton\\u0026source\\u003dlmns\\u0026tbm\\u003disch',
          null,
          null,
          'Images',
          true,
          null,
          null,
          null,
          null,
          'IMAGES',
          [ 6 ],
          null,
          null,
          6
        ]
      ],
      [
        [
          '/search?q\\u003dfront+florestan+fargetton\\u0026source\\u003dlmns\\u0026tbm\\u003dnws',
          null,
          null,
          'News',
          false,
          null,
          null,
          null,
          null,
          'NEWS',
          [ 10 ],
          null,
          null,
          10
        ],
        [
          '/search?q\\u003dfront+florestan+fargetton\\u0026source\\u003dlmns\\u0026tbm\\u003dvid',
          null,
          null,
          'Videos',
          false,
          null,
          null,
          null,
          null,
          'VIDEOS',
          [ 13 ],
          null,
          null,
          13
        ],
        [
          '/search?q\\u003dfront+florestan+fargetton\\u0026source\\u003dlmns\\u0026tbm\\u003dbks',
          null,
          null,
          'Books',
          false,
          null,
          null,
          null,
          null,
          'BOOKS',
          [ 2 ],
          null,
          null,
          2
        ],
        [
          '//maps.google.com/maps?q\\u003dfront+florestan+fargetton\\u0026source\\u003dlmns\\u0026entry\\u003dmt',
          null,
          null,
          'Maps',
          false,
          null,
          null,
          null,
          null,
          'MAPS',
          [ 8 ],
          null,
          null,
          8,
          true
        ],
        [
          '/travel/flights?q\\u003dfront+florestan+fargetton\\u0026source\\u003dlmns\\u0026tbm\\u003dflm',
          null,
          null,
          'Flights',
          false,
          null,
          null,
          null,
          null,
          'FLIGHTS',
          [ 20 ],
          null,
          null,
          20,
          true
        ],
        [
          '/search?q\\u003dfront+florestan+fargetton\\u0026source\\u003dlmns\\u0026tbm\\u003dfin',
          null,
          null,
          'Finance',
          false,
          null,
          null,
          null,
          null,
          'FINANCE',
          [ 22 ],
          null,
          null,
          22
        ]
      ]
    ],
    0,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    true,
    null,
    null,
    [
      3,
      'Looks like there aren’t any matches for your search',
      null,
      null,
      null,
      [
        'Search tips',
        [
          null,
          "\\u003cul\\u003e\\u003cli\\u003eMake sure all words are spelled correctly\\u003c/li\\u003e\\u003cli\\u003eTry different or more general words\\u003c/li\\u003e\\u003cli\\u003eTry fewer words\\u003c/li\\u003e\\u003c/ul\\u003eCheck out \\u003ca href\\u003d'https://support.google.com/websearch/answer/134479?hl\\u003den'\\u003eother tips\\u003c/a\\u003e for searching on Google"
        ]
      ],
      null,
      null,
      0
    ],
    [
      [ false ],
      false,
      null,
      null,
      null,
      null,
      [ true, false ],
      null,
      null,
      0.715434
    ],
    false,
    [ [ { '444381080': [] } ] ],
    [ [ { '444381080': [] } ] ]
  ],
  date: 2024-03-02T04:52:26.095Z,
  version: '1.8.0'
}

Node.js v21.2.0

```

Merci <3

**Comment by Pivouane** [comment]
Envoie ta ref
